repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
    #
    # Go Build
    #
    -   id: go-build-repo-mod
    #
    # Go Mod Tidy
    #
    -   id: go-mod-tidy
    #
    # Go Test
    #
    -   id: go-test-mod
    #
    # Go Vet
    #
    -   id: go-vet-mod
    #
    # Revive
    #
    -   id: go-revive
    #
    # GoSec
    #
    -   id: go-sec-mod
    #
    # StructSlop
    #
    #-   id: go-structslop-mod
    #
    # Formatters
    #
    -   id: go-fumpt        # replaces go-fmt
    -   id: go-imports      # replaces go-fmt
    #
    # Style Checkers
    #
    -   id: go-lint
    -   id: go-critic
